# Generated by Django 4.1 on 2023-02-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="conference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("authors", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("image", models.ImageField(blank=True, upload_to="images/")),
                ("where", models.CharField(max_length=100)),
                ("year", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("authors", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("image", models.ImageField(blank=True, upload_to="images/")),
                ("where", models.CharField(max_length=100)),
                ("doi", models.CharField(blank=True, max_length=100)),
                ("year", models.CharField(max_length=10)),
                ("description", models.TextField(blank=True)),
            ],
        ),
    ]
