# Generated by Django 4.1 on 2023-02-17 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="pubconf",
            field=models.CharField(default="publication", max_length=100),
        ),
        migrations.AlterField(
            model_name="conference",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="conference",
            name="where",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="publication",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="publication",
            name="where",
            field=models.CharField(max_length=200),
        ),
    ]
