# Generated by Django 4.1 on 2023-02-17 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0002_publication_pubconf_alter_conference_title_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="conference",
        ),
    ]
