# Generated by Django 4.1 on 2023-02-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0003_delete_conference"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="pdf",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
