# Generated by Django 4.1 on 2023-02-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0004_publication_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="abstract",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
