# Generated by Django 4.1 on 2023-02-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0005_publication_abstract"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="pdf",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
