# Generated by Django 4.1 on 2023-02-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0006_alter_publication_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="link",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
